### ISSUE TITLE
Potential Violation Detected

### ISSUE THREAD

**Issue by assignguard-support** [CSCI202FORTWAYNE/CSCI101-0AC-FA22-Demos#1]
Hey CSCI202FORTWAYNE!

This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.

At your earliest convenience, please do one of the following:
  - disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
  - remove any content could be in violation of copyright law
  - remove any content could be in violation of an institution's academic integrity policy

Please feel free to continue any discussion here. Thanks!

**Comment by assignguard-support** [comment]
:wave: gentle reminder!

**Comment by avenable11** [comment]
I am an instructor, and this repository is a public host of my in-class demos.  There is no academic integrity violation here this code is being provided to students in my class.
